import MenuProvider from "@/context/useContextMenu";
import ScreenBreakPointProvider from "@/context/useContextScreenBreakPoints";
import "./globals.css"; //
import { Inter, Marcellus } from "next/font/google";
import type { Metadata } from "next";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import NavMenu from "@/components/NavMenu";
import { i18n } from "i18n-config";

interface RootLayoutProps {
    children: React.ReactNode;
}

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });
const marcellus = Marcellus({ subsets: ["latin"], weight: "400" });

export default function RootLayout({ children }: RootLayoutProps) {
    return (
        <html lang="en">
            <body className={`${inter.className} ${marcellus.className}`}>
                <MenuProvider>
                    <ScreenBreakPointProvider>
                        <NavMenu />
                        <Header />
                        {children}
                        <Footer />
                    </ScreenBreakPointProvider>
                </MenuProvider>
            </body>
        </html>
    );
}

export async function generateStaticParams() {
    return i18n.locales.map((locale) => ({ lang: locale }));
}
