import NavMenu from "@/components/NavMenu";
import Footer from "@/components/Footer";
import "./globals.css";
import type { Metadata } from "next";
import { Inter, Marcellus } from "next/font/google";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const inter = Inter({ subsets: ["latin"] });
const marcellus = Marcellus({ subsets: ["latin"], weight: "400" });

export default function RootLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <html lang="en">
            <body className={`${inter.className} ${marcellus.className}`}>
                <NavMenu />
                {children}
                <Footer />
            </body>
        </html>
    );
}
